name: Tag

on:
  push:
    tags:
      - v*

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    permissions:
      contents: write
    needs:
      - build
    uses: ./.github/workflows/release.yml
